/**
 * Staff Access Types
 * Types for staff tokens, sessions, and role-based access control
 */

/** Staff roles for event modules */
export type StaffRole = 'check_in' | 'bracket' | 'results' | 'admin';

/** Token status */
export type TokenStatus = 'active' | 'expired' | 'revoked';

/**
 * Staff Access Token
 * Generated by admin/organizer to give staff access to specific modules
 */
export interface StaffAccessToken {
  id: string;
  event_id: string;
  role: StaffRole;
  token: string; // UUID único para acesso
  nickname?: string; // Ex: "Check-in Mesa 1", "Mat 2"
  created_by?: string; // user_id do organizador
  created_at: Date;
  expires_at?: Date; // null = não expira até evento terminar
  last_accessed_at?: Date;
  status: TokenStatus;
  max_uses?: number; // null = ilimitado
  current_uses: number;
  metadata?: Record<string, unknown>; // dados extras (device info, etc)
}

/**
 * Staff Session
 * Active connection from a staff member
 */
export interface StaffSession {
  id: string;
  token_id: string; // referência ao StaffAccessToken
  token: string; // o token usado para conectar
  event_id: string;
  role: StaffRole;
  connected_at: Date;
  last_activity_at: Date;
  socket_id?: string; // WebSocket socket.id
  device_info?: DeviceInfo;
  is_online: boolean;
}

/**
 * Device information for session tracking
 */
export interface DeviceInfo {
  user_agent?: string;
  platform?: string;
  screen_width?: number;
  screen_height?: number;
  ip_address?: string;
}

/**
 * Staff Access Request - used when validating token on entry
 */
export interface StaffAccessRequest {
  token: string;
  event_id: string;
  device_info?: DeviceInfo;
}

/**
 * Staff Access Response - returned after token validation
 */
export interface StaffAccessResponse {
  valid: boolean;
  session?: StaffSession;
  error?: string;
  redirect_path?: string; // Path to redirect to (e.g., /staff/:eventId/check-in)
}

/**
 * Connected Client info for Master panel
 */
export interface ConnectedClient {
  session_id: string;
  token_id: string;
  nickname?: string;
  role: StaffRole;
  connected_at: Date;
  last_activity_at: Date;
  is_online: boolean;
  device_info?: DeviceInfo;
}

/**
 * Token Generation Request
 */
export interface GenerateTokenRequest {
  event_id: string;
  role: StaffRole;
  nickname?: string;
  expires_at?: Date;
  max_uses?: number;
}

/**
 * QR Code/Link data for staff access
 */
export interface StaffAccessLink {
  token: StaffAccessToken;
  url: string; // Full URL for access
  qr_data: string; // Data to encode in QR code
}

/**
 * Role permissions configuration
 */
export const ROLE_PERMISSIONS: Record<StaffRole, {
  label: string;
  description: string;
  modules: string[];
  color: string;
}> = {
  check_in: {
    label: 'Check-in Staff',
    description: 'Acesso ao módulo de check-in e pesagem',
    modules: ['check_in', 'attendance'],
    color: 'bg-green-500',
  },
  bracket: {
    label: 'Bracket/Mat Staff',
    description: 'Acesso ao módulo de brackets e resultados de lutas',
    modules: ['bracket', 'fights', 'results_write'],
    color: 'bg-blue-500',
  },
  results: {
    label: 'Results Viewer',
    description: 'Visualização somente leitura de resultados',
    modules: ['results_read'],
    color: 'bg-purple-500',
  },
  admin: {
    label: 'Administrador',
    description: 'Acesso completo a todos os módulos',
    modules: ['all'],
    color: 'bg-red-500',
  },
};

/**
 * Helper to check if a role has permission for a module
 */
export function hasPermission(role: StaffRole, module: string): boolean {
  const permissions = ROLE_PERMISSIONS[role];
  return permissions.modules.includes('all') || permissions.modules.includes(module);
}

/**
 * Generate a unique token string
 */
export function generateTokenString(): string {
  // Use crypto.randomUUID if available, otherwise fallback
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  // Fallback for older environments
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

/**
 * Build staff access URL
 */
export function buildStaffAccessUrl(
  baseUrl: string,
  eventId: string,
  token: string,
  role?: StaffRole
): string {
  if (role) {
    return `${baseUrl}/staff/${eventId}/${role}/${token}`;
  }
  return `${baseUrl}/staff/${eventId}/${token}`;
}
