// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://otqzzllevufcxbpeavmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90cXp6bGxldnVmY3hicGVhdm1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODkyNTEsImV4cCI6MjA3MTc2NTI1MX0.siWeTTxga1b62Cc9y3lt1MJwfrSejPhw6en3ZuQYack";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);